version: "3.4"

services:

  customerdb:
    container_name: customerdb
    image: postgres
    environment:
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
     POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - ./customer/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped   

  querydb:
    container_name: querydb
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./account.query/postgres_init.sql:/docker-entrypoint-initdb.d/postgres_init.sql
    ports:
      - "5433:5432"
    restart: unless-stopped    

  rabbitmq:
    container_name: "rabbit_container"
    image: "rabbitmq:3.8-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SOMETHINGSECRET"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

  cmddb:
    container_name: "cmddb"
    image: mongo
    restart: always
    ports:
        - "27017:27017"

  customer-service:
    image: bank/customer-service-api
    container_name: customer-service
    build:
      context: ./customer
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - customerdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customerdb:5432/customerdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=rabbitmq
      - SPRING_RABBITMQ_PASSWORD=rabbitmq

  account-cmd:
    image: bank/account-cmd-service-api
    container_name: account-cmd-service
    build:
      context: ./account.cmd
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
      - cmddb
    environment:
      - SPRING_DATA_MONGODB_HOST=cmddb
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=accountcmdb
      - SPRING_RABBITMQ_HOST=rabbitmq
      - spring_RABBITMQ_PORT=5672
      - spring_RABBITMQ_USERNAME=rabbitmq
      - spring_RABBITMQ_PASSWORD=rabbitmq

  account-query:
    image: bank/account-query-service-api
    container_name: account-query-service
    build:
      context: ./account.query
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
      - querydb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://querydb:5433/accountingdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=rabbitmq
      - SPRING_RABBITMQ_PASSWORD=rabbitmq

volumes:
  customerdb:
  mongo:
  accounting_db: